# Generated by Django 4.1.2 on 2022-10-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_autor_livro_copialivro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='data_de_falecimento',
            field=models.DateField(blank=True, null=True, verbose_name='Falecimento (✟)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento (★)'),
        ),
    ]
